SHELL=/usr/local/bin/bash
COLORTERM=truecolor
XPC_FLAGS=0x0
TERM_PROGRAM_VERSION=1.95.3
__CFBundleIdentifier=com.microsoft.VSCode
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.lE0WHJd7Jl/Listeners
MallocNanoZone=0
HOMEBREW_PREFIX=/opt/homebrew
PWD=/Users/ethanbrandwien/Desktop/2830/final
LOGNAME=ethanbrandwien
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code-2.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
COMMAND_MODE=unix2003
HOME=/Users/ethanbrandwien
LANG=en_US.UTF-8
TMPDIR=/var/folders/5y/kfb94n9x52d3l23x5r0f2cgr0000gn/T/
GIT_ASKPASS=/Applications/Visual Studio Code-2.app/Contents/Resources/app/extensions/git/dist/askpass.sh
INFOPATH=/opt/homebrew/share/info:/opt/homebrew/share/info:
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
TERM=xterm-256color
USER=ethanbrandwien
VSCODE_GIT_IPC_HANDLE=/var/folders/5y/kfb94n9x52d3l23x5r0f2cgr0000gn/T/vscode-git-b6e92f7deb.sock
HOMEBREW_CELLAR=/opt/homebrew/Cellar
SHLVL=1
HOMEBREW_REPOSITORY=/opt/homebrew
XPC_SERVICE_NAME=0
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code-2.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
TERM_PROGRAM=vscode
_=/usr/local/bin/python3
